server:
  port: 10001

logging:
  level:
    org.apache.http.wire: trace
    org.apache.http.headers: trace
    com.liujc.service.UserService: trace
#debug: true
spring:
  application:
    name: springboot-feign-client
  devtools:
    livereload:
      port: 15730

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
###设置feign客户端超时时间
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 3000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 3000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: springboot-feign-client-10001
    #访问路径可以显示IP地址
    prefer-ip-address: true
