server:
  port: 8001

logging:
  level:
    org.apache.http.wire: trace
    org.apache.http.headers: trace
debug: true
spring:
  devtools:
    livereload:
      port: 35730

feign:
  httpclient:
    enabled: true