spring:
  application:
    name: springboot-zipkin-server
  main:
    allow-bean-definition-overriding: true
server:
   port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
